<?php

/* Based on https://github.com/fabiopaiva/zf2-navigation-bootstrap3 */

/* @var $container Laminas\Navigation\Navigation */
$container = $this->container;
$layoutAttributes = [
    'dropdown' => 'class="dropdown menu" data-dropdown-menu',
    'vertical' => 'class="vertical menu accordion-menu" data-accordion-menu data-submenu-toggle="true"',
];
?>
<ul <?php echo $layoutAttributes[$layout]; ?> test-data="test">
    <?php foreach ($container as $page) : ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Laminas\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php $showChildren = $this->themeSetting('nav_show_levels'); ?>

        <li<?php if ($page->isActive()) echo ' class="active"' ?>>
            <a class="nav-header" href="<?php echo $page->getHref() ?>" <?php if ($page->getTarget() != "") : ?> target="<?php echo $page->getTarget(); ?>" <?php endif; ?>>
                <?php if ($page->get("icon") !== "") : ?>
                    <span class="<?php echo $page->get("icon"); ?>"></span>
                <?php endif; ?>
                <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
            </a>
        </li>
        <?php endforeach ?>
</ul>