<div id="search-archives">
    <div class="search-archives-container">
        <img id="search-archives-logo" alt="Search Archives logo" src="../../../themes/foundation/asset/img/nhprc-logo-l.jpg" />
        <div style="width: 100%; color: #777; font-weight: 500; font-size: 2em">Search Archives</div>
        <span style="font-size: 0.8em; color: #777;">Lorem Ipsum Dolor Sit Amet, Consectetur Adipiscing Elit, Sed Do Eiusmod Tempor Incididunt</span>
        <div class="select-dropdowns">

            <?php
            $search = $this->plugin('facetSelect');
            $categorySearch = $this->ListCategory();
            $translate = $this->plugin('translate');
            // Subject
            $res = $categorySearch->getValueValues("items", 3, "eq", array("item_set_id" => array(7285), "site_id" => 21));
            foreach ($res as $value) {
                $subject[]["value"] = $value["label"];
            }
            echo $search("dcterms_subject_ss", $subject, array("placeholder" => 'Subject')); // look at search/facet-select.phtml

            // Audience Education Level
            $res = $categorySearch->getValueValues("items", 46, "eq", array("item_set_id" => array(7285), "site_id" => 21));

            foreach ($res as $value) {
                $edu_level[]["value"] = $value["label"];
            }
            echo $search("dcterms_educationLevel", $edu_level, array("placeholder" => 'Education Level')); // look at search/facet-select.phtml

            ?>
        </div>
        <!-- <form action="/" class="search-form" class="input-group">
<input type="text" name="fulltext_search" 
    placeholder="<?php echo $translate('Search site...'); ?>"
    aria-label="<?php echo $translate('Search'); ?>" class="input-group-field">
<div class="input-group-button">
<button type="submit" class="button"></button>
</div>
</form> -->
    </div>
</div>