<?php
$translate = $this->plugin('translate');
$tags = $this->plugin('showTags');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$showLayout = $this->themeSetting('show_layout');
$mediaDisplay = $this->themeSetting('media_display');
$galleryDisplay = (isset($mediaDisplay)) ? strpos($mediaDisplay, 'gallery') : false;
$tracksPresent = $this->DetectTracks($itemMedia);

if ($galleryDisplay) {
  $this->headLink()->appendStylesheet($this->assetUrl('vendor/lightgallery/css/lightgallery-bundle.min.css'));
  $this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/lightgallery.min.js'));
  $this->headScript()->appendFile($this->assetUrl('js/show.js'));
  $this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/plugins/thumbnail/lg-thumbnail.min.js'));
  $this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/plugins/video/lg-video.min.js'));
  $this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/plugins/pager/lg-pager.min.js'));
  $this->headScript()->appendFile($this->assetUrl('vendor/lightgallery/plugins/zoom/lg-zoom.min.js'));

  $lightMedia = [];
  $otherMedia = [];
  $whitelist = ['image/bmp', 'image/gif', 'image/jpeg', 'image/png', 'image/svg+xml'];
  foreach ($itemMedia as $media) {
    $mediaType = $media->mediaType();
    $mediaRenderer = $media->renderer();
    if (in_array($mediaType, $whitelist) || (strpos($mediaType, 'video') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
      $lightMedia[] = $media;
    } else {
      $otherMedia[] = $media;
    }
  }
}
?>

<div class="resource-title">
  <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
  <h3 class="label"><?php echo $translate('Item'); ?></h3>
</div>

<div class="grid-x">
  <?php if ($galleryDisplay) : ?>
    <?php if (count($lightMedia) > 0) : ?>
      <div id="itemfiles" class="<?php echo $mediaDisplay; ?>">
        <?php foreach ($lightMedia as $media) : ?>
          <?php
          $mediaType = $media->mediaType();
          $mediaRenderer = $media->renderer();
          $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source();
          $subHtml = "<div class='lg-caption'>" . $media->displayTitle() . "</div>";
          ?>

          <?php if (strpos($mediaType, 'image') !== false) : ?>
            <div data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('square')); ?>" class="media resource" data-sub-html="<?php echo $subHtml; ?>">
              <?php echo $media->render(); ?>
            </div>
          <?php elseif (strpos($mediaRenderer, 'youtube') !== false) : ?>
            <a class="media resource" data-src="<?php echo $source; ?>" data-poster="<?php echo $media->thumbnailDisplayUrl('square'); ?>" data-sub-html="<?php echo $subHtml; ?>">
            </a>
          <?php else : ?>
            <?php
            $trackHtml = '';
            if ($tracksPresent) {
              $originalFilename = pathinfo($media->source(), PATHINFO_FILENAME);
              $trackHtml .=  '"tracks": [';
              foreach ($otherMedia as $key => $media) {
                $trackHtml .= $this->OutputTrack($media, $originalFilename);
                unset($otherMedia[$key]);
              }
              $trackHtml = rtrim($trackHtml, ',');
              $trackHtml .= '],';
            }
            ?>
            <a class="media resource" data-video='{"source": [{"src":"<?php echo $source; ?>", "type":"<?php echo $mediaType; ?>"}], <?php echo $trackHtml; ?> "attributes": {"preload": false, "controls": true}}' data-download-url="<?php echo $source; ?>" data-poster="<?php echo $media->thumbnailDisplayUrl('square'); ?>" data-sub-html="<?php echo $subHtml; ?>">
              <img class="img-responsive" src="<?php echo $media->thumbnailDisplayUrl('square'); ?>" />
            </a>
          <?php endif; ?>
        <?php endforeach; ?>
      </div>
    <?php endif; ?>
  <?php else : ?>
    <?php if (count($itemMedia) > 0) : ?>
      <div class="<?php echo ($embedMedia) ? 'media-embeds-custom' : 'media-list' ?>" style="width:100%">
        <h4>Media</h4>
        <?php foreach ($itemMedia as $media) : ?>
          <?php echo ($embedMedia) ? $media->render() : $media->linkPretty(); ?>
        <?php endforeach; ?>
        <div class="right-sidebar cell medium-3">
          <?php
          //echo $rightSidebarBlockContent->getBlocks();
          echo $tags($item);
          ?>
        </div>
      </div>
    <?php endif; ?>


  <?php endif; ?>

  <div id="resource-values" class="<?php echo ($showLayout == 'inline') ? 'inline' : 'stack'; ?>">
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $item->displayValues(); ?>
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0) : ?>
      <dl>
        <div class="property">
          <dt><?php echo $translate('Item sets'); ?></dt>
          <div class="values">
            <?php foreach ($itemSets as $itemSet) : ?>
              <dd class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></dd>
            <?php endforeach; ?>
          </div>
        </div>
      </dl>
    <?php endif; ?>

    <?php if ($galleryDisplay || $mediaDisplay == 'single') : ?>
      <?php $mediaList = ($galleryDisplay) ? $otherMedia : $itemMedia; ?>
    <?php endif; ?>

    <?php if (($this->siteSetting('show_attached_pages', true)) && ($sitePages = $item->sitePages($site->id()))) : ?>
      <dl>
        <div class="property">
          <dt><?php echo $translate('Site pages'); ?></dt>
          <div class="values">
            <?php foreach ($sitePages as $sitePage) : ?>
              <dd class="value"><?php echo $sitePage->link($sitePage->title()); ?></dd>
            <?php endforeach; ?>
          </div>
        </div>
      </dl>
    <?php endif; ?>
    <!-- Via a standard partial. -->
    <?php //echo $this->partial('common/comment', ['resource' => $resource]); 
    ?>

    <?php //$this->trigger('view.show.after'); 
    ?>
  </div>
</div>
<script type="text/javascript">
  var found = true;
  var value = $("dl div.property dt:contains('Item sets')")
    .siblings("div.values")
    .find("dd.value a")
    .text();
  var url = window.location.href;
  var baseUrl = url.split("/").slice(0, -2).join("/");
  if (value == "Publications") {
    sub_url = "/publications"
  } else if (value == "Speeches/ Writings") {
    sub_url = "/speeches-writings"
  } else if (value == "Audio/ Moving Images") {
    sub_url = "/audio-moving-images"
  } else {
    found = false;
  }
  if (found) {
    var link = $("<a></a>");
    link.attr("href", baseUrl + sub_url);
    link.text(value);
    link.attr("class", "active");
    $('.sidebar-menu-container .main-menu-title').append(link).append(' > ');
  }
  $('.sidebar-menu-container .main-menu-title').append($('.resource-title h2 span').text())
</script>