<?php
$translate = $this->plugin('translate');
$itemTitle = $media->item()->title();
$itemSet = current($media->item()->itemSets())->title();
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>

<div class="resource-title">
<?php echo $this->pageTitle($media->displayTitle(), 2); ?>
<h3 class="label"><?php echo $translate('Media'); ?></h3>
</div>
<?php $this->trigger('view.show.before'); ?>
<?php echo $media->render(); ?>
<?php echo $media->displayValues(); ?>
<?php $this->trigger('view.show.after'); ?>
<script type="text/javascript">
  var found = true;
  var value =  '<?php echo $itemSet; ?>';
  var url = window.location.href;
  var baseUrl = url.split("/").slice(0, -2).join("/");
  if (value == "Publications") {
    sub_url = "/publications"
  } else if (value == "Office of the President") {
    sub_url = "/office-of-the-president"
  } else if (value == "Audio/ Moving Images") {
    sub_url = "/audio-moving-images"
  } else {
    found = false;
  }
  if (found) {
    var link = $("<a></a>");
    link.attr("href", baseUrl + sub_url);
    link.text(value);
    link.attr("class", "active");
    $('.sidebar-menu-container .main-menu-title').append(link).append(' > ');
  }
  var linkItem = $("<a></a>");
  linkItem.attr("href", baseUrl + '/item/' + '<?php echo $media->item()->id();?>');
  linkItem.text('<?php echo $itemTitle;?>');
  linkItem.attr("class", "active");
  $('.sidebar-menu-container .main-menu-title').append(linkItem).append(' > ')

  var media = '<?php echo $media->displayTitle();?>'
  $('.sidebar-menu-container .main-menu-title').append(media)

</script>