<?php
$this->htmlElement('body')->appendAttribute('class', 'page ' . $page->slug());
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination',
                                       $this->themeSetting('show_page_pagination_config'));
?>

<?php
$nav = $site->publicNav();

$container = $nav->getContainer();
$activePage = $nav->findActive($container);

if ($activePage):
?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs()->setPartial('common/foundation-breadcrumbs'); ?></nav>
    <?php endif; ?>
<?php endif; ?>


<?php $this->trigger('view.show.before'); ?>

<div id="blocks" class="blocks">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
