<?php
$this->htmlElement('body')->appendAttribute('class', 'page ' . $page->slug());
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination',
                                       $this->themeSetting('show_page_pagination_config'));
?>

<?php
$nav = $site->publicNav();

$container = $nav->getContainer();
$activePage = $nav->findActive($container);

if ($activePage):
?>
    <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs"><?php echo $nav->breadcrumbs()->setPartial('common/foundation-breadcrumbs'); ?></nav>
    <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
    <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu wide" data-sticky-container>
        <div class="sticky" data-sticky data-anchor="blocks">
            <?php echo $nav->menu()->setUlClass('vertical menu')->renderSubMenu(); ?>
        </div>
    </nav>
    <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<?php 
 // Only for home page
 if ($nav->findActive($container)["page"]->getParams()['page-slug'] == "home" && $nav->findActive($container)["page"]->getParams()['site-slug'] == "archives"):
    echo $this->partial('common/search-home'); 
 endif;
?>
<div id="blocks" class="blocks">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
<?php echo $this->sitePagePagination(); ?>
<?php endif; ?>
