<?php
//$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$stylesheet = $this->themeSetting('stylesheet');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
if (isset($stylesheet)) {
    $this->headLink()->prependStylesheet($this->assetUrl("css/$stylesheet.css"));
} else {
    $this->headLink()->prependStylesheet($this->assetUrl('css/default.css'));
}
$this->headLink()->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css');
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/foundation/foundation.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/wsu.js'));

$this->jsTranslate();
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$userBar = $this->userBar();

$navLayout = ($this->themeSetting('nav_layout')) ? $this->themeSetting('nav_layout') : 'dropdown';
$this->htmlElement('body')->appendAttribute('class', $navLayout . '-menu');
if ($userBar) {
    $this->htmlElement('body')->appendAttribute('class', 'user-bar');
}

$banner = $this->themeSettingAssetUrl('banner');
$bannerWidth = ($this->themeSetting('banner_width')) ? $this->themeSetting('banner_width') : '';
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_', '-', $this->themeSetting('banner_position')) : 'center';
$logo = $this->themeSettingAssetUrl('logo');
if ($logo) :
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>
    <style>
        .banner {
            height: <?php echo ($bannerHeight !== '') ? $bannerHeight : 'auto'  ?>;
            align-items: <?php echo $bannerPosition; ?>;
        }

        <?php if ($bannerHeightMobile !== '') : ?>@media screen and (max-width:640px) {
            .banner {
                height: <?php echo $bannerHeightMobile; ?>;
            }
        }

        <?php endif; ?>
    </style>
</head>

<?php echo $this->htmlElement('body'); ?>

<div id="offCanvas" class="off-canvas position-left" data-off-canvas>
    <?php echo $site->publicNav()->menu()->setPartial('common/foundation-navigation.phtml')->renderPartialWithParams(['layout' => 'vertical']); ?>
    <div class="search">
        <?php echo $this->partial('common/search-form'); ?>
    </div>
</div>
<div class="off-canvas-content" data-off-canvas-content>
    <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
    <?php echo $userBar; ?>
    <header>
        <?php if ($navLayout == 'vertical') : ?>
            <?php echo $this->partial('common/header-vertical'); ?>
        <?php else : ?>
            <?php echo $this->partial('common/header-dropdown'); ?>
        <?php endif; ?>
        <?php if ($banner) : ?>
            <div class="banner <?php echo $bannerWidth; ?>">
                <img src="<?php echo $this->themeSettingAssetUrl('banner'); ?>" title="Banner">
            </div>
        <?php endif; ?>
    </header>
    <div id="content" role="main">
        <div class="sidebar-menu">
            <div class="sidebar-menu-container">
                <?php
                $nav = $site->publicNav();
                $container = $nav->getContainer();
                $activePage = $nav->findActive($container);
                // if we are at a child menu, get the parent and then show all children
                if ($activePage && $activePage['depth'] == 1) {
                    //var_dump($activePage['page']->getParent());
                    $activePage['page'] = $activePage['page']->getParent();
                }
                
                ?>
                <div class="main-menu-title"><?php echo  !empty($activePage['page']) ? '<a href="'.$activePage['page']->getHref().'"/>'.$activePage['page']->getLabel().'</a>' : ""; ?> <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a> </div>
                <?php if ($activePage) : ?>
                    <?php if ($activePage['page']->hasPages()) : ?>
                        <nav class="sub-menu wide">
                            <div class="sub-menu-container" data-anchor="blocks">
                                <?php echo $nav->menu()->setUlClass('vertical menu')->renderSubMenu(); ?>
                            </div>
                        </nav>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <div class="sidebar-last-items">
                <div class="last-items-title">LATEST UPDATES</div>
                <?php
                $categorySearch = $this->ListLastItems();
                $params = $categorySearch->getLastItemsInserted();
                //var_dump($params['resources'][0]->getJsonLd()["o:created"]);
                //var_dump($params['resources'][0]->value("dcterms:date")->value());
                // echo ($params['resources'][0]->title());
                // echo($params['resources'][0]->value("dcterms:description"));
                $timeline_objects = [];
                foreach ($params['resources'] as $resource_item) {
                    if ($resource_item->value("dcterms:date") != null) {
                        $array = [];
                        $array["time"] = $resource_item->value("dcterms:date")->value();
                        $array["body"][0]["tag"] = "h2";
                        $array["body"][0]["content"] = $resource_item->title();
                        $array["body"][1]["tag"] = "p";
                        $array["body"][1]["content"] = $resource_item->value("dcterms:description")->value();
                        array_push($timeline_objects, $array);
                    }
                }
                $json = json_encode($timeline_objects);
                //echo ($json);
                echo $this->partial('common/block-layout/browse-preview', [
                    'resourceType' => $params['resourceType'],
                    'resources' => $params['resources'],
                    'heading' => $params['heading'],
                    'linkText' => $params['link-text'],
                    'components' => $params['components'],
                    'query' => $params['query'],
                ]);

                ?>
            </div>
        </div>
        <button class="openbtn" onclick="openNav()">&#9776;</button>
        <div id="main-content">
            <?php
            //var_dump($activePage['page']->getLabel());
            echo $this->content;
            //echo $this->partial('common/block-layout/timeline', ['data'=>$json]);
            ?>
        </div>

    </div>
    <footer>
        <?php if ($footerContent = $this->themeSetting('footer')) : ?>
            <?php echo $footerContent; ?>
        <?php else : ?>
            <?php echo $this->translate('Powered by Omeka S'); ?>
        <?php endif; ?>
    </footer>
</div>
<script>
    $(document).foundation();
    /* Set the width of the sidebar to 250px and the left margin of the page content to 250px */
    function openNav() {
        $(".sidebar-menu").css("width", "250px");
        //document.getElementById("main").style.marginLeft = "250px";
    }

    /* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
    function closeNav() {
        $(".sidebar-menu").css("width", "0px");
        //document.getElementById("main").style.marginLeft = "0";
    }
</script>
</body>

</html>